### PR TITLE
Created Travis CI testing for the repository.

### PR DESCRIPTION
**Pull request by hellothisisMatt**
Using small test data, modified tests for fasta files and created a test for fastq files.
Created .travis.yml file required for Travis CI.

### CODE REVIEW

**Comment by hellothisisMatt** [comment]
Hey @peterk87! I'm hoping the CI-Test passes, but if it doesn't you don't have to review this PR. It seems like this is the only way I can trigger CI Testing via Travis.

**Comment by peterk87** [comment]
Looks like you need to add `--force` to `$ conda config --remove channels defaults`:

`The command "conda config --remove channels defaults" failed and exited with 1 during .`

Also you may need to add the bioconda channel and other channels it depends on:

```
conda config --add channels defaults
conda config --add channels conda-forge
conda config --add channels bioconda
```

according to https://bioconda.github.io/#set-up-channels

**Comment by hellothisisMatt** [comment]
I changed a couple of install steps, and it seems to work on a local instance of Travis CI. I cleaned up that entire conda install block so it looks nicer :smile:

**Comment by hellothisisMatt** [comment]
@peterk87 Woohoo it passes! Just assigning you as a reviewer in case you wanted to look at the changes.

**Pull request merged**
